export const GET_DISTRIBUTIONS = 'GET_DISTRIBUTIONS';
export const GET_MANUFACTURERSINFO = 'GET_MANUFACTURERSINFO';
export const GET_FURNITURES = 'GET_FURNITURES';
export const GET_FURNITURE = 'GET_FURNITURE';
export const GET_BIOGRAPHIES = 'GET_BIOGRAPHIES';
export const GET_USERS = 'GET_USERS';
export const GET_SINGLE_USER = 'GET_SINGLE_USER';
export const GET_USER = 'GET_USER';
export const DELETE_CART_ITEM = 'DELETE_CART_ITEM'

export default {
  GET_DISTRIBUTIONS,
  GET_MANUFACTURERSINFO,
  GET_FURNITURES,
  GET_FURNITURE,
  GET_BIOGRAPHIES,
  GET_USERS,
  GET_SINGLE_USER,
  GET_USER,
  DELETE_CART_ITEM
};
