export const GET_USERS = "GET_USERS"
export const GET_DISTRIBUTIONS = "GET_DISTRIBUTIONS"
export const GET_MANUFACTURERSINFO = "GET_MANUFACTURERSINFO"
export const GET_FURNITURES = "GET_FURNITURES"


export default {
  GET_USERS,
  GET_DISTRIBUTIONS,
  GET_MANUFACTURERSINFO,
  GET_FURNITURES,

};


